routes/web.php
<?php
//
///*
//|--------------------------------------------------------------------------
//| Web Routes
//|--------------------------------------------------------------------------
//|
//| Here is where you can register web routes for your application. These
//| routes are loaded by the RouteServiceProvider within a group which
//| contains the "web" middleware group. Now create something great!
//|
//*/
//
//Route::get('/', function () {
//    return view('welcome');
//});
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'IndexController@index')->name('index');
Route::get('/about', 'IndexController@about')->name('about');
Route::get('/building', 'IndexController@building')->name('building');
Route::get('/repair', 'IndexController@repair')->name('repair');
Route::get('/portfolio', 'IndexController@portfolio')->name('portfolio');
Route::get('/portfolio/{id}', 'IndexController@portfolioShow')->name('portfolio.show');
Route::get('/contacts', 'IndexController@contacts')->name('contacts');
Route::post('/contacts', 'IndexController@sendContacts')->name('contact.send');
Route::post('/building', 'IndexController@sendBuilding')->name('building.send');
Route::get('/sitemap.xml', 'IndexController@sitemaps')->name('sitemap');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Auth::routes();
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'IndexController@index')->name('admin.index');

    Route::get('/setting', 'IndexController@index')->name('admin.setting');
    Route::post('/setting', 'IndexController@update')->name('admin.setting.update');

    Route::resource('/contact', 'ContactController', ['as' => 'admin']);
    Route::resource('/portfolio', 'PortfolioController', ['as' => 'admin']);
    Route::get('/portfolio/{id}/hide', 'PortfolioController@hide', ['as' => 'admin'])->name('admin.portfolio.hide');
    Route::post('/portfolio/{id}/position', 'PortfolioController@changePosition', ['as' => 'admin'])->name('admin.portfolio.position');

    Route::match(['get', 'post'],'/comments/create', 'CommentsController@create')->name('admin.comments.create');
    Route::match(['get', 'post'],'/comments/update/{id}', 'CommentsController@update')->name('admin.comments.update');
    Route::get('/comments/delete/{id}', 'CommentsController@delete')->name('admin.comments.delete');
    Route::get('/comments', 'CommentsController@index')->name('admin.comments.index');

});

resources/views/admin/navigation.blade.php
	<header>
			<div class="container-fluid p-0">
				<div class="row m-0">
					<div class="col-12 p-0">
						<div class="nav_container">
							<a href="/" class="logo_container">
							    <img src="{{ asset('images/main/logo_white.svg') }}" alt="">
							</a>
							<ul class="nav_menu">
                                <li class="nav_item">
                                    <a href="{{ route('admin.portfolio.index') }}">
                                        <div class="img_container"><img src="{{ asset('images/admin/briefcase.svg') }}" alt=""></div>
                                        <div class="text"><p>Портфолио</p></div>
                                    </a>
                                </li>
                                <li class="nav_item">
                                    <a href="{{ route('admin.comments.index') }}">
                                        <div class="img_container"><img src="{{ asset('images/admin/briefcase.svg') }}" alt=""></div>
                                        <div class="text"><p>Комментарии</p></div>
                                    </a>
                                </li>
                                <li class="nav_item">
                                    <a href="{{ route('admin.contact.index') }}">
                                        <div class="img_container"><img src="{{ asset('images/admin/contact.svg') }}" alt=""></div>
                                        <div class="text"><p>Контакты</p></div>
                                    </a>
                                </li>
                                <li class="nav_item">
                                    <a href="{{ route('admin.setting') }}">
                                        <div class="img_container"><img src="{{ asset('images/admin/settings_icon.png') }}" alt=""></div>
                                        <div class="text"><p>Настройки</p></div>
                                    </a>
                                </li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</header>

resources/views/admin/setting.blade.php
@extends('admin.layouts.app_admin')

@section('wrap-class')
        <div id="wrapper-settings">
@endsection

@section('navigation')
    @include('admin.navigation')
@endsection

@section('content')

    <main>
        <div class="section_main">
            <div class="container-fluid p-0">
                <div class="row m-0">
                    <div class="col-12 p-0">
                        <div class="header_search">
                            <div class="title">
                                <h1>Настройки</h1>
                            </div>
                            <div class="btn_container">
                                <form id="logout-form" action="{{ route('logout') }}" method="POST">
                                    @csrf
                                    <button type="submit">Выйти</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (\Session::has('error'))
                    <div class="alert alert-danger">
                        <ul>
                            @foreach (\Session::get('error') as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (\Session::has('success'))
                    <div class="alert alert-success">
                        <ul>
                            @foreach (\Session::get('success') as $success)
                                <li>{{$success}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="settings_container">
                    <div class="settings_block row m-0">
                        <div class="col-12 p-0">


                            <form class="settings_form" action="{{route('admin.setting.update', $user)}}" method="post">
                                <div class="form_title">
                                    <h1>Изменить пароль</h1>
                                </div>
                                <div class="form_settings_pass">
                                    <div class="row m-0">
                                        <div class="col-4 p-0">
                                            <div class="input_container">
                                                <p class="input_lable">Старый пароль*</p>
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="password" name="current-password">
                                            </div>
                                        </div>
                                        <div class="col-4 p-0">
                                            <div class="input_container">
                                                <p class="input_lable">Новый пароль*</p>
                                                <input type="password" name="password">
                                            </div>
                                        </div>
                                        <div class="col-4 p-0">
                                            <div class="input_container">
                                                <p class="input_lable">Подтверждение*</p>
                                                <input type="password" name="password_confirmation" >
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="btn_container">
                                    <button class="custom_btn save" type="submit">
                                        <span>Сохранить</span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

@endsection