routes/web.php
<?php
//
///*
//|--------------------------------------------------------------------------
//| Web Routes
//|--------------------------------------------------------------------------
//|
//| Here is where you can register web routes for your application. These
//| routes are loaded by the RouteServiceProvider within a group which
//| contains the "web" middleware group. Now create something great!
//|
//*/
//
//Route::get('/', function () {
//    return view('welcome');
//});
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'IndexController@index')->name('index');
Route::get('/about', 'IndexController@about')->name('about');
Route::get('/building', 'IndexController@building')->name('building');
Route::get('/repair', 'IndexController@repair')->name('repair');
Route::get('/portfolio', 'IndexController@portfolio')->name('portfolio');
Route::get('/portfolio/{id}', 'IndexController@portfolioShow')->name('portfolio.show');
Route::get('/contacts', 'IndexController@contacts')->name('contacts');
Route::post('/contacts', 'IndexController@sendContacts')->name('contact.send');
Route::post('/building', 'IndexController@sendBuilding')->name('building.send');
Route::get('/sitemap.xml', 'IndexController@sitemaps')->name('sitemap');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Auth::routes();
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'IndexController@index')->name('admin.index');

    Route::get('/setting', 'IndexController@index')->name('admin.setting');
    Route::post('/setting', 'IndexController@update')->name('admin.setting.update');

    Route::resource('/contact', 'ContactController', ['as' => 'admin']);
    Route::resource('/portfolio', 'PortfolioController', ['as' => 'admin']);
    Route::get('/portfolio/{id}/hide', 'PortfolioController@hide', ['as' => 'admin'])->name('admin.portfolio.hide');
    Route::post('/portfolio/{id}/position', 'PortfolioController@changePosition', ['as' => 'admin'])->name('admin.portfolio.position');

    Route::match(['get', 'post'],'/comments/create', 'CommentsController@create')->name('admin.comments.create');
    Route::match(['get', 'post'],'/comments/update/{id}', 'CommentsController@update')->name('admin.comments.update');
    Route::get('/comments/delete/{id}', 'CommentsController@delete')->name('admin.comments.delete');
    Route::get('/comments', 'CommentsController@index')->name('admin.comments.index');

});

app/Portfolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

use Spatie\MediaLibrary\Conversion\Conversion;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\Models\Media;

class Portfolio extends Model
{
    protected $fillable = [
        'category',
        'main_photo',
        'mini_photo',
        'slider',
        'title',
        'desc',
        'content',
        'position',
        'status'
    ];

    public $casts = [
        'slider' => 'array',
    ];

    public static function boot() {
        parent::boot();

        static::deleting(function($portfolio) { // before delete() method call this

            if ($portfolio->main_photo) {
                foreach (json_decode($portfolio->main_photo) as $image)
                    if ($image) {
                        Storage::disk('upload')->delete($image);
                    }
            }

            if ($portfolio->mini_photo) {
                Storage::disk('upload')->delete($portfolio->mini_photo);
            }

            if ($portfolio->slider) {
                foreach (json_decode($portfolio->slider) as $image)
                    if ($image) {
                        Storage::disk('upload')->delete($image);
                    }
            }

        });

    }

    /**
     * Set the polymorphic relation.
     *
     * @return mixed
     */
    public function media()
    {
        // TODO: Implement media() method.
    }

    /**
     * Move a file to the medialibrary.
     *
     * @param string|\Symfony\Component\HttpFoundation\File\UploadedFile $file
     *
     * @return \Spatie\MediaLibrary\FileAdder\FileAdder
     */
    public function addMedia($file)
    {
        // TODO: Implement addMedia() method.
    }

    /**
     * Copy a file to the medialibrary.
     *
     * @param string|\Symfony\Component\HttpFoundation\File\UploadedFile $file
     *
     * @return \Spatie\MediaLibrary\FileAdder\FileAdder
     */
    public function copyMedia($file)
    {
        // TODO: Implement copyMedia() method.
    }

    /**
     * Determine if there is media in the given collection.
     *
     * @param $collectionMedia
     *
     * @return bool
     */
    public function hasMedia(string $collectionMedia = ''): bool
    {
        // TODO: Implement hasMedia() method.
    }

    /**
     * Get media collection by its collectionName.
     *
     * @param string $collectionName
     * @param array|callable $filters
     *
     * @return \Illuminate\Support\Collection
     */
    public function getMedia(string $collectionName = 'default', $filters = [])
    {
        // TODO: Implement getMedia() method.
    }

    /**
     * Remove all media in the given collection.
     *
     * @param string $collectionName
     */
    public function clearMediaCollection(string $collectionName = 'default')
    {
        // TODO: Implement clearMediaCollection() method.
    }

    /**
     * Remove all media in the given collection except some.
     *
     * @param string $collectionName
     * @param \Spatie\MediaLibrary\Media[]|\Illuminate\Support\Collection $excludedMedia
     *
     * @return string $collectionName
     */
    public function clearMediaCollectionExcept(string $collectionName = 'default', $excludedMedia = [])
    {
        // TODO: Implement clearMediaCollectionExcept() method.
    }

    /**
     * Determines if the media files should be preserved when the media object gets deleted.
     *
     * @return bool
     */
    public function shouldDeletePreservingMedia()
    {
        // TODO: Implement shouldDeletePreservingMedia() method.
    }

    /**
     * Cache the media on the object.
     *
     * @param string $collectionName
     *
     * @return mixed
     */
    public function loadMedia(string $collectionName)
    {
        // TODO: Implement loadMedia() method.
    }

    public function addMediaConversion(string $name): Conversion
    {
        // TODO: Implement addMediaConversion() method.
    }

    public function registerMediaConversions(Media $media = null)
    {
        // TODO: Implement registerMediaConversions() method.
    }

    public function registerMediaCollections()
    {
        // TODO: Implement registerMediaCollections() method.
    }

    public function registerAllMediaConversions()
    {
        // TODO: Implement registerAllMediaConversions() method.
    }
}

app/Http/Controllers/Admin/PortfolioController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Portfolio;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\ImageManagerStatic as Image;
use Intervention\Image\Constraint;

class PortfolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $portfolios = Portfolio::orderBy('category')->orderBy('position')->get();
//        $positions = Portfolio::select('position')->orderBy('position')->get();
//        dd($positions[0]['position']);
        return view('admin.portfolios.index', [
            'portfolios' => $portfolios
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $positions = Portfolio::select('position')->get();
        return view('admin.portfolios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $max_position = Portfolio::select('position')->max('position');
        $data = $request->all();

        $validator = Validator::make($data, [
            'main_photo' => 'required|mimes:jpg,jpeg,png',
            'mini_photo' => "required|mimes:jpg,jpeg,png",
            'category' => "required",
            'title' => "required|max:70",
            'desc' => "required|max:302",
            'content' => "required|max:710",
//            'slider_photo' => "required|min:3",
        ]);


        if ($validator->fails()) {
            return redirect('admin/portfolio/create')
                ->withErrors($validator)
                ->withInput();
        }
        //save main photo
        if ($request->hasFile('main_photo')) {

            $image = $this->upload($request->file('main_photo'), Config::get('settings.main_photo_max'));
            if ($image['status'] === true) {
                $main_photo[] = $image['fullFileName'];
            } else {
                return redirect()->back()->withErrors(['image' => $image['status']]);
            }

            $image = $this->upload($request->file('main_photo'), Config::get('settings.main_photo_min'));
            if ($image['status'] === true) {
                $main_photo[] = $image['fullFileName'];
            } else {
                return redirect()->back()->withErrors(['main_photo' => $image['status']]);
            }
            $data['main_photo'] = json_encode($main_photo);
        }

        //save mini photo
        if ($request->hasFile('mini_photo')) {

            $image = $this->upload($request->file('mini_photo'), Config::get('settings.mini_photo'));
            if ($image['status'] === true) {
                $data['mini_photo'] = $image['fullFileName'];
            } else {
                return redirect()->back()->withErrors(['mini_photo' => $image['status']]);
            }
        }

        //Проверка отправил ли пользователь изображение
        if ($request->hasFile('slider_photo')) {
            foreach ($request->slider_photo as $key => $slider) {
                $image = $this->upload($slider, Config::get('settings.slider_photo'));
                if ($image['status'] === true) {
                    $sliders[] = $image['fullFileName'];
                } else {
                    return redirect()->back()->withErrors(['slider_photo' => $image['status']]);
                }
            }
            $data['slider'] = json_encode($sliders);
        }
        $data['position'] = (int)$max_position + 1;
        $portfolio = Portfolio::create($data);

//        if ($request->hasFile('slider_photo')) {
//            foreach ($request->slider_photo as $key => $slider)
//            $portfolio->addMedia($slider)->toMediaCollection('sliders');
//
//        }

        if ($portfolio) return redirect()->route('admin.portfolio.index');
        else  return redirect()->back()->withErrors(['save' => 'something wrong']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $portfolio = Portfolio::find($id);
        return view('admin.portfolios.edit', [
            'portfolio' => $portfolio
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        dd($request->all());
        $portfolio = Portfolio::find($id);
        $data = $request->all();
//        if(isset($data['slider']) && ($data['slider'])) {
//            $data['slider'] = array_values(array_diff($data['slider'], $data['del_slider']));
//        }



        $validator = Validator::make($data, [
            'main_photo' => 'required_without:main_present|mimes:jpg,jpeg,png',
            'mini_photo' => "required_without:mini_present|mimes:jpg,jpeg,png",
            'category' => "required",
            'title' => "required|max:70",
            'desc' => "required|max:302",
            'content' => "required|max:710",
//            'slider_photo' => "required_without:slider-0,slider-1,slider-2",
        ]);
        $data['slider'] = $portfolio->slider;

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        
        //Deleting photo
        if ($data['close_main_photo']) Storage::disk('upload')->delete($data['close_main_photo']);
        if ($data['close_mini_photo']) Storage::disk('upload')->delete($data['close_mini_photo']);
        foreach ($data['del_slider'] as $key => $del_slider)
            if ($del_slider) {
                Storage::disk('upload')->delete($del_slider);
                unset($data['slider'][$key]);
            }

            //doing new array after deleting (new index)
//        if ($data['slider'])
//                    dd($data['slider']);
//        $data['slider'] = array_values($data['slider']);

        //save main photo
        if ($request->hasFile('main_photo')) {

            $image = $this->upload($request->file('main_photo'), Config::get('settings.main_photo_max'));
            if ($image['status'] === true) {
                $main_photo[] = $image['fullFileName'];
            } else {
                return redirect()->back()->withErrors(['image' => $image['status']]);
            }

            $image = $this->upload($request->file('main_photo'), Config::get('settings.main_photo_min'));
            if ($image['status'] === true) {
                $main_photo[] = $image['fullFileName'];
            } else {
                return redirect()->back()->withErrors(['main_photo' => $image['status']]);
            }
            $data['main_photo'] = json_encode($main_photo);
        }

        //save mini photo
        if ($request->hasFile('mini_photo')) {

            $image = $this->upload($request->file('mini_photo'), Config::get('settings.mini_photo'));
            if ($image['status'] === true) {
                $data['mini_photo'] = $image['fullFileName'];
            } else {
                return redirect()->back()->withErrors(['mini_photo' => $image['status']]);
            }
        }

//        //Проверка отправил ли пользователь изображение
        if ($request->hasFile('slider_photo')) {
            foreach ($request->slider_photo as $key => $slider) {
                $image = $this->upload($slider, Config::get('settings.slider_photo'));
                if ($image['status'] === true) {
                    $data['slider'][] = $image['fullFileName'];
                } else {
                    return redirect()->back()->withErrors(['slider_photo' => $image['status']]);
                }
            }
        }
        $update_portfolio = $portfolio->update($data);

        if ($update_portfolio) return redirect()->route('admin.portfolio.index');
        return redirect()->back()->withErrors(['save' => 'something wrong']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $portfolio = Portfolio::find($id);

        $portfolio->delete();

        return redirect()->back();

    }

    public function hide($id)
    {

        $portfolio = Portfolio::find($id);
        ($portfolio->status) ? $portfolio->update(['status' => 0]) : $portfolio->update(['status' => 1]);
        return redirect()->back();
    }

    public function changePosition($id, Request $request)
    {

        $portfolio = Portfolio::find($id);

        if ($portfolio->position != $request->position) {

            $portfolio_old = Portfolio::where('position', $request->position)->first();

            if ($portfolio_old) $portfolio_old->update(['position' => $portfolio->position]);

            $portfolio->update(['position' => $request->position]);

        }


        return redirect()->back();
    }


    public function upload($file, $size_path)
    {
        $path = 'portfolio' . '/' . date('F') . date('Y') . '/';

        $filename = basename($file->getClientOriginalName(), '.' . $file->getClientOriginalExtension());
        $filename_counter = 1;

        // Make sure the filename does not exist, if it does make sure to add a number to the end 1, 2, 3, etc...

resources/views/admin/portfolios/create.blade.php
@extends('admin.layouts.app_admin')

@section('wrap-class')
	<div id="wrapper-product-info">
@endsection

@section('navigation')
	@include('admin.navigation')
@endsection

@section('content')
<main id="page-portfolio">
	<div class="section_main">
		<div class="container-fluid p-0">
			<div class="row m-0">
				<div class="col-12 p-0">
					<div class="header_search">
						<a href="{{ route('admin.portfolio.index') }}" class="title">
							<img src="{{ asset('images/admin/arrow_left.png') }}" alt="">
							<span>Создание портфолио</span>
						</a>
					</div>
				</div>
			</div>
			<div class="product_info_container">

				<form id="create-form" action="{{ route('admin.portfolio.store') }}" method="post" enctype="multipart/form-data">
						{{ csrf_field() }}
						@include('admin.portfolios.partials.form')
				</form>



			</div>
		</div>
	</div>
</main>
@endsection

resources/views/admin/portfolios/edit.blade.php
@extends('admin.layouts.app_admin')

@section('wrap-class')
	<div id="wrapper-product-info">
@endsection

@section('navigation')
	@include('admin.navigation')
@endsection

@section('content')
	<main id="page-portfolio">
		<div class="section_main">
			<div class="container-fluid p-0">
				<div class="row m-0">
					<div class="col-12 p-0">
						<div class="header_search">
							<a href="{{ route('admin.portfolio.index') }}" class="title">
								<img src="{{ asset('images/admin/arrow_left.png') }}" alt="">
								<span>Изменение портфолио</span>
							</a>
						</div>
					</div>
				</div>
				<div class="product_info_container">
					<form id="create-form" action="{{route('admin.portfolio.update', $portfolio)}}" method="post" enctype="multipart/form-data">
						<input type="hidden" name="_method" value="put">
						{{ csrf_field() }}
						@include('admin.portfolios.partials.form')
					</form>



				</div>
			</div>
		</div>
	</main>
@endsection

resources/views/admin/portfolios/index.blade.php
@extends('admin.layouts.app_admin')


@section('wrap-class')
    <div id="wrapper-products">
        @endsection

        @section('navigation')
            @include('admin.navigation')
        @endsection

        @section('content')

            <main>
                <div class="section_main">
                    <div class="container-fluid p-0">
                        <div class="row m-0">
                            <div class="col-12 p-0">
                                <div class="header_search">
                                    <div class="title">
                                        <h1>Портфолио</h1>
                                    </div>
                                    <div class="add_btn">
                                        <a href="{{route('admin.portfolio.create')}}"><img
                                                src="{{ asset('images/admin/add.svg') }}" alt=""></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table_main row m-0">
                            <div class="col-12 p-0">
                                <div class="table_container">
                                    <table>
                                        <thead>
                                        <tr>
                                            <th>
                                                <p>Заголовок</p>
                                            </th>
                                            <th>
                                                <p>Краткое описание</p>
                                            </th>
                                            <th>
                                                <p>Категория</p>
                                            </th>
                                            <th>
                                                <p>Статус</p>
                                            </th>
                                            <th>
                                                <p>Позиция</p>
                                            </th>
                                            <th>
                                                <p>Действие</p>
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        @forelse($portfolios as $portfolio)
                                            @php $portfolio->main_photo = json_decode($portfolio->main_photo);
                                            @endphp
                                            <tr>
                                                <th>
                                                    <div class="product_container">
                                                        <div class="product_image">
                                                            @isset($portfolio->main_photo[1])
                                                                <img
                                                                    src=" {{ Storage::disk('upload')->url($portfolio->main_photo[1]) }}"
                                                                    alt="">
                                                            @endisset
                                                        </div>
                                                        <div class="product_name">
                                                            <p>{{ $portfolio->title ?? '' }}</p>
                                                        </div>
                                                    </div>
                                                </th>
                                                <th>
                                                    <p>{{ $portfolio->desc ?? '' }}</p>
                                                </th>
                                                <th>
                                                    <p>
                                                        @if($portfolio->category) Строительство @else Ремонт @endif
                                                    </p>
                                                </th>

                                                <th>
                                                    <p>@if ( isset($portfolio->status) && ($portfolio->status))
                                                            Активна @else Скрыта @endif</p>
                                                </th>
                                                <th>
                                                    {{--<p>{{ $portfolio->position ?? '' }}</p>--}}
                                                    <select class="portfolio_position" data-action="{{ route('admin.portfolio.position', $portfolio->id)  }}"
                                                            name="position">
                                                        @foreach($portfolios as $key => $item)
                                                            <option value="{{$item->position}}" @if($item->position == $portfolio->position) selected @endif> {{$key + 1}}</option>
                                                        @endforeach

                                                    </select>
                                                </th>
                                                <th>
                                                    <div class="order_button">
                                                        <img class="btn_show"
                                                             src="{{ asset('images/admin/button_detailed_icon.png') }}"
                                                             alt="">
                                                        <div class="detailed_block">
                                                            <a class="text_btn"
                                                               href="{{route('admin.portfolio.edit', $portfolio)}}">Редактировать</a>
                                                            <form class="text_btn delete"
                                                                  action="{{route('admin.portfolio.destroy', $portfolio)}}"
                                                                  method="post">
                                                                <input type="hidden" name="_method" value="delete">
                                                                {{ csrf_field() }}
                                                                <button type="submit" class="text_btn"
                                                                        href="{{route('admin.portfolio.destroy', $portfolio)}}">
                                                                    Удалить
                                                                </button>
                                                            </form>
                                                            <a class="text_btn"
                                                               href="{{route('admin.portfolio.hide', $portfolio->id)}}">@if ($portfolio->status)
                                                                    Скрыть @else  Показать @endif</a>
                                                        </div>
                                                    </div>
                                                </th>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td>
                                                    <h3 style="text-alight:center">Данные отсутствуют</h3>
                                                </td>
                                            </tr>
                                        @endforelse

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </main>

@endsection