routes/web.php
<?php
//
///*
//|--------------------------------------------------------------------------
//| Web Routes
//|--------------------------------------------------------------------------
//|
//| Here is where you can register web routes for your application. These
//| routes are loaded by the RouteServiceProvider within a group which
//| contains the "web" middleware group. Now create something great!
//|
//*/
//
//Route::get('/', function () {
//    return view('welcome');
//});
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'IndexController@index')->name('index');
Route::get('/about', 'IndexController@about')->name('about');
Route::get('/building', 'IndexController@building')->name('building');
Route::get('/repair', 'IndexController@repair')->name('repair');
Route::get('/portfolio', 'IndexController@portfolio')->name('portfolio');
Route::get('/portfolio/{id}', 'IndexController@portfolioShow')->name('portfolio.show');
Route::get('/contacts', 'IndexController@contacts')->name('contacts');
Route::post('/contacts', 'IndexController@sendContacts')->name('contact.send');
Route::post('/building', 'IndexController@sendBuilding')->name('building.send');
Route::get('/sitemap.xml', 'IndexController@sitemaps')->name('sitemap');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Auth::routes();
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'IndexController@index')->name('admin.index');

    Route::get('/setting', 'IndexController@index')->name('admin.setting');
    Route::post('/setting', 'IndexController@update')->name('admin.setting.update');

    Route::resource('/contact', 'ContactController', ['as' => 'admin']);
    Route::resource('/portfolio', 'PortfolioController', ['as' => 'admin']);
    Route::get('/portfolio/{id}/hide', 'PortfolioController@hide', ['as' => 'admin'])->name('admin.portfolio.hide');
    Route::post('/portfolio/{id}/position', 'PortfolioController@changePosition', ['as' => 'admin'])->name('admin.portfolio.position');

    Route::match(['get', 'post'],'/comments/create', 'CommentsController@create')->name('admin.comments.create');
    Route::match(['get', 'post'],'/comments/update/{id}', 'CommentsController@update')->name('admin.comments.update');
    Route::get('/comments/delete/{id}', 'CommentsController@delete')->name('admin.comments.delete');
    Route::get('/comments', 'CommentsController@index')->name('admin.comments.index');

});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'phone_1',
        'phone_2',
        'email',
        'address',
        'map',
        'link_f',
        'link_i'
    ];

}

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contact =  Contact::first();
        return view('admin.contacts.index', [
            'contact' => $contact
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = Contact::find($id);
        return view('admin.contacts.edit', [
            'contact' => $contact
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // СДЕЛАТЬ НОРМАЛЬНУЮ РЕГУЛЯРКУ ДЛЯ ТЕЛЕФОНОВ
        $contact = Contact::find($id);
        $data = $request->except('_method', '_token');
//        dd($data);
        $validator = Validator::make($data, [
            'phone_1' => "required|string|min:11",
            'phone_2' => "string|min:11",
            'address' => "required|string",
            'map' => "required|string",
            'email' => "email",
        ]);


        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        // Преобразовать телефоны перед сохранением

        $contact->update($data);

        config(['MAIL_USERNAME_TO' => 'katorif@ukr.net']);

        return redirect()->route('admin.contact.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/contacts/edit.blade.php
@extends('admin.layouts.app_admin')

@section('wrap-class')
	<div id="wrapper-product-info">
@endsection

@section('navigation')
	@include('admin.navigation')
@endsection

@section('content')
	<main>
		<div class="section_main">
			<div class="container-fluid p-0">
				<div class="row m-0">
					<div class="col-12 p-0">
						<div class="header_search">
							<a href="{{ route('admin.contact.index') }}" class="title">
								<img src="{{ asset('images/admin/arrow_left.png') }}" alt="">
								<span>Контакты - изменение</span>
							</a>
						</div>
					</div>
				</div>
				<div class="product_info_container">
					<form id="create-form" action="{{route('admin.contact.update', $contact)}}" method="post" enctype="multipart/form-data">
						<input type="hidden" name="_method" value="put">
						{{ csrf_field() }}
						@include('admin.contacts.partials.form')
					</form>



				</div>
			</div>
		</div>
	</main>
@endsection

resources/views/admin/contacts/index.blade.php
@extends('admin.layouts.app_admin')


@section('wrap-class')
    <div id="wrapper-products">
        @endsection

        @section('navigation')
            @include('admin.navigation')
        @endsection

        @section('content')
            @isset($contact->id)
            <main>
                <div class="section_main">
                    <div class="container-fluid p-0">
                        <div class="row m-0">
                            <div class="col-12 p-0">
                                <div class="header_search">
                                    <div class="title">
                                        <h1>Контакты</h1>
                                    </div>
                                    <div class="add_btn">
                                        <a href="{{route('admin.contact.edit', $contact->id)}}"><img
                                                src="{{ asset('images/admin/edit.svg') }}" alt=""></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table_main row m-0">
                            <div class="col-12 p-0">
                                <div class="table_container">
                                    <table>
                                        <thead>
                                        <tr>
                                            <th><p>#</p></th>
                                            <th><p>Поле</p></th>
                                            <th><p>Данные</p></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th><p>1</p></th>
                                                <th>
                                                    <p>Телефон №1</p>
                                                </th>

                                                <th> <p>{{ isset($contact->phone_1) ? $contact->phone_1 : ''}}</p></th>
                                            </tr>
                                            <tr>
                                                <th><p>2</p></th>
                                                <th>
                                                    <p>Телефон №2</p>
                                                </th>

                                                <th> <p>{{ isset($contact->phone_2) ? $contact->phone_2 : ''}}</p></th>
                                            </tr>
                                            <tr>
                                                <th><p>3</p></th>
                                                <th>
                                                    <p>Почта</p>
                                                </th>

                                                <th> <p>{{ isset($contact->email) ? $contact->email : ''}}</p></th>
                                            </tr>
                                            <tr>
                                                <th><p>4</p></th>
                                                <th>
                                                    <p>Адресс</p>
                                                </th>
                                                <th> <p>{{ isset($contact->address) ? $contact->address : ''}}</p></th>
                                            </tr>
                                            <tr>
                                                <th><p>5</p></th>
                                                <th>
                                                    <p>Координаты</p>
                                                </th>
                                                <th> <p>{{ isset($contact->map) ? $contact->map : ''}}</p></th>
                                            </tr>
                                            <tr>
                                                <th><p>6</p></th>
                                                <th>
                                                    <p>Ссылка в фейсбук</p>
                                                </th>
                                                <th> <p>{{ isset($contact->link_f) ? $contact->link_f : ''}}</p></th>
                                            </tr>
                                            <tr>
                                                <th><p>7</p></th>
                                                <th>
                                                    <p>Ссылка в инстаграм</p>
                                                </th>
                                                <th> <p>{{ isset($contact->link_i) ? $contact->link_i : ''}}</p></th>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                @endisset
            </main>




@endsection